import Script from 'next/script';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Model Details — Klyxe',
  description: 'Detailed benchmark results for individual AI models across code, reasoning, instruction following, translation, and speed tests.',
  openGraph: {
    title: 'AI Model Details — Klyxe',
    description: 'Full benchmark breakdown for individual AI models — code execution, reasoning scores, speed comparisons.',
  },
};

export default function ModelPage() {
  return (
    <>
      <Script src="/style-spacing.css" strategy="afterInteractive" />
      <Script src="/style.css" strategy="afterInteractive" />
      <Script src="/animations.css" strategy="afterInteractive" />
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js" strategy="afterInteractive" />

      <div id="page-root">
        <div className="page-loading">Loading model data&hellip;</div>
      </div>

      <Script id="model-logic" strategy="afterInteractive">{`
function esc(str){return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function scoreClass(score){if(score>=71)return 'score-high';if(score>=31)return 'score-medium';return 'score-low';}
function scoreBadgeClass(score){if(score>=71)return 'score-high';if(score>=31)return 'score-medium';return 'score-low';}
function passBadge(passed,total){var pct=total>0?passed/total*100:0;var cls=scoreBadgeClass(pct);return '<span class="pass-badge '+cls+'">'+passed+'/'+total+' passed</span>';}
var PROMPTS={code:{prime:'Write a Python function called <code>is_prime(n)</code> that returns <code>True</code> if n is prime, <code>False</code> otherwise.',fibonacci:'Write a Python function called <code>fibonacci(n)</code> that returns the nth Fibonacci number (0-indexed).',palindrome:'Write a Python function called <code>is_palindrome(s)</code> that returns <code>True</code> if the string is a palindrome (ignore case and spaces).'},reasoning:{syllogism:'All bloops are razzies. All razzies are lazzies. Are all bloops lazzies?',speed_math:'Train A travels 120 km in 2 hours. Train B travels 180 km in 3 hours. Which train is faster?',river_crossing:'A farmer needs to cross a river with a fox, a chicken, and a bag of grain. The boat fits only the farmer and one item. The fox will eat the chicken if left alone together, and the chicken will eat the grain if left alone together. What does the farmer take across first?',coin_flip:'I flipped a fair coin 3 times and got heads each time. What is the probability the next flip is heads?',counting:'How many letters are in the word "MISSISSIPPI"?',knights_knaves:'On an island, knights always tell the truth and knaves always lie. A person says "I am a knight." What are they?',scheduling:'Alice is free Mon/Wed/Fri. Bob is free Tue/Thu/Fri. Carol is free Mon/Thu/Sat. Is there a day all three can meet on a weekday?',base_rate:'A disease affects 1 in 1000 people. A test is 99% accurate. You test positive. Are you more likely sick or healthy?',deduction:'All mammals are warm-blooded. Whales are mammals. Are whales warm-blooded?',word_problem:'A shirt costs $6. A hat costs $2 more than the shirt. How much do they cost together?'},instruction:{json:'Return a JSON object with exactly these 3 keys: "name", "age", "city". Use any realistic values.',list:'List exactly 5 programming languages, numbered 1 through 5.',word_count:'Describe the city of Paris in exactly 3 sentences.'},translation:{en_ru:'Translate the following sentence to Russian: "The future of artificial intelligence is both exciting and challenging."',ru_en:'Translate the following sentence to English: "Искусственный интеллект меняет мир быстрее, чем мы успеваем осознать."',en_es:'Translate the following sentence to Spanish: "Technology is transforming the way we live and work every day."'},speed:{simple:'What is 2+2?',medium:'Explain what machine learning is in 2-3 sentences.',long:'Write a detailed explanation of how neural networks work, covering layers, weights, activation functions, and backpropagation.'}};
var REASONING_ANSWERS={syllogism:'Yes — valid syllogism (Barbara form)',speed_math:'Same speed — both travel at exactly 60 km/h',river_crossing:'Chicken — take it first so nothing gets eaten',coin_flip:'1/2 — each flip is independent',counting:'11 — M(1) I(4) S(4) P(2)',knights_knaves:'Knight — a knight always tells the truth',scheduling:'No — there is no time slot that works for all',base_rate:'Healthy — base rate dominates (rare disease)',deduction:'Yes — follows from the given premises',word_problem:'14 — solve the system of equations'};
var TRANSLATION_LABELS={en_ru:'English → Russian',ru_en:'Russian → English',en_es:'English → Spanish'};
var TRANSLATION_CHECKS={en_ru:function(d){return 'Cyrillic ratio: '+(d.cyrillic_ratio*100).toFixed(0)+'% (threshold: >20%)';},ru_en:function(d){return 'Latin ratio: '+(d.latin_ratio*100).toFixed(0)+'% (threshold: >60%)';},en_es:function(d){return 'Spanish keywords found: '+d.keywords_found+' (threshold: ≥3)';}};
var INSTR_LABELS={json:'Return a JSON object with exactly 3 keys: "name", "age", "city"',list:'List exactly 5 programming languages, numbered 1–5',word_count:'Describe Paris in exactly 3 sentences'};
var INSTR_CHECK={json:function(d){return 'Check: valid JSON with all 3 keys present · '+(d.reason==='ok'?'✅ Valid':'❌ '+d.reason);},list:function(d){return 'Check: count numbered lines · found '+d.found+', expected '+d.expected;},word_count:function(d){return 'Check: count sentences · found '+d.found+', expected '+d.expected;}};
function renderCodeSection(tests){if(!tests.code||!tests.code.details)return'';var details=tests.code.details;var avg=tests.code.avg_score;var cls=scoreClass(avg);var totalPassed=0,totalCases=0;details.forEach(function(t){totalPassed+=t.passed;totalCases+=t.total;});var body=details.map(function(t){var rows=(t.details||[]).map(function(c){var bc=scoreBadgeClass(c.passed?100:0);return '<tr><td><code>'+esc(c.input)+'</code></td><td><code>'+esc(c.expected)+'</code></td><td><code>'+esc(c.got)+'</code></td><td class="case-status"><span class="pass-badge '+bc+'">'+(c.passed?'✅':'❌')+'</span></td></tr>';}).join('');var pct=t.total>0?t.passed/t.total*100:0;var bc=scoreBadgeClass(pct);return '<div class="test-item"><div class="test-item-header"><div><div class="test-item-name">'+esc(t.test)+'</div><div class="qa-label" style="margin-top:4px;">Prompt</div><div class="qa-box" style="margin-bottom:0;">'+(PROMPTS.code[t.test]||t.test)+'</div></div>'+passBadge(t.passed,t.total)+'</div><table class="cases-table"><thead><tr><th>Input</th><th>Expected</th><th>Got</th><th>Result</th></tr></thead><tbody>'+rows+'</tbody></table></div>';}).join('');return makeCategoryCard('💻','Code — Real Execution','3 functions · '+totalPassed+'/'+totalCases+' test cases passed',avg,cls,body);}
function renderReasoningSection(tests){if(!tests.reasoning||!tests.reasoning.details)return'';var d=tests.reasoning;var avg=d.score;var cls=scoreClass(avg);var body=d.details.map(function(t){var correct=t.correct;var bc=scoreBadgeClass(correct?100:0);return '<div class="test-item"><div class="test-item-header"><div class="test-item-name">'+esc(t.test.replace('_',' '))+'</div><span class="pass-badge '+bc+'">'+(correct?'✅ Correct':'❌ Wrong')+'</span></div><div class="qa-block"><div class="qa-label">Question</div><div class="qa-box">'+esc(PROMPTS.reasoning[t.test]||t.test)+'</div><div class="qa-label">Model answered</div><div class="qa-box '+(correct?'answer-box':'wrong-box')+'">'+esc(t.answer_given||'—')+'</div><div class="qa-label">Correct answer</div><div class="qa-box">'+esc(t.expected_answer||REASONING_ANSWERS[t.test]||(t.correct?t.answer_given:'—'))+'</div></div></div>';}).join('');return makeCategoryCard('🧠','Reasoning — Verified Answers',d.correct+'/'+d.total+' correct',avg,cls,body);}
function renderInstructionSection(tests){if(!tests.instruction||!tests.instruction.details)return'';var d=tests.instruction;var avg=d.avg_score;var cls=scoreClass(avg);var body=d.details.map(function(t){var bc=scoreBadgeClass(t.score);var checkText=INSTR_CHECK[t.test]?INSTR_CHECK[t.test](t):'Score: '+t.score;return '<div class="test-item"><div class="test-item-header"><div class="test-item-name">'+esc(t.test.replace('_',' '))+'</div><span class="pass-badge '+bc+'">'+t.score+'/100</span></div><div class="qa-block"><div class="qa-label">Task</div><div class="qa-box">'+esc(INSTR_LABELS[t.test]||t.test)+'</div><div class="qa-label">Grading method</div><div class="qa-box answer-box">'+esc(checkText)+'</div></div></div>';}).join('');return makeCategoryCard('📋','Instruction Following','Format compliance · 3 tasks',avg,cls,body);}
function renderTranslationSection(tests){if(!tests.translation||!tests.translation.details)return'';var d=tests.translation;var avg=d.avg_score;var cls=scoreClass(avg);var body='<div class="test-item">'+d.details.map(function(t){var bc=scoreBadgeClass(t.score);var checkText=TRANSLATION_CHECKS[t.test]?TRANSLATION_CHECKS[t.test](t):'Score: '+t.score;return '<div class="trans-item"><div><div class="trans-direction">'+(TRANSLATION_LABELS[t.test]||t.test)+'</div><div class="qa-label" style="margin-top:6px;">Prompt</div><div class="qa-box" style="margin-bottom:4px;">'+esc(PROMPTS.translation[t.test]||t.test)+'</div><div class="trans-detail">'+esc(checkText)+'</div></div><span class="pass-badge '+bc+'">'+t.score+'/100</span></div>';}).join('')+'</div>';return makeCategoryCard('🌍','Translation','EN↔RU · EN→ES · script detection',avg,cls,body);}
function renderSpeedSection(tests){if(!tests.speed||!tests.speed.details)return'';var d=tests.speed;var items=d.details.map(function(t){return '<div class="speed-item"><div class="speed-item-label">'+esc(t.test)+' prompt</div><div class="speed-item-val">'+Math.round(t.tokens_per_sec)+'<span class="speed-item-unit"> tok/s</span></div><div style="font-size:11px;color:var(--text-tertiary);margin-top:4px;">'+t.tokens+' tokens · '+t.time.toFixed(2)+'s</div><div class="qa-label" style="margin-top:8px;font-size:10px;">Prompt used</div><div style="font-size:11px;color:var(--color-on-surface);background:var(--color-surf-cont-highest);border-radius:6px;padding:6px 10px;margin-top:2px;">'+esc(PROMPTS.speed[t.test]||t.test)+'</div></div>';}).join('');var body='<div class="speed-grid">'+items+'</div><p style="font-size:12px;color:var(--text-tertiary);margin-top:12px;">⚠️ Speed depends on server load at test time (~03:00 UTC). Numbers reflect real-world performance but may vary at peak hours.</p>';var avg=d.avg_tokens_per_sec;return makeCategoryCard('⚡','Speed — Tokens Per Second','Avg '+Math.round(avg)+' tok/s · 3 prompt lengths',avg,'',body,true);}
function makeCategoryCard(icon,name,sub,score,cls,bodyHtml,isSpeed){var barFill=isSpeed?'':('<div class="cat-bar-wrap"><div class="cat-bar-fill '+cls+'" style="width:'+Math.min(score,100)+'%"></div></div>');var scoreDisp=isSpeed?'<span class="cat-score-pill" style="color:#0b8043;">'+Math.round(score)+'<small> t/s</small></span>':'<span class="cat-score-pill '+cls+'">'+Math.round(score)+'<small>/100</small></span>';return '<div class="test-category"><div class="test-category-header" onclick="toggleCat(this)"><span class="test-cat-icon">'+icon+'</span><div class="test-cat-info"><div class="test-cat-name">'+name+'</div><div class="test-cat-sub">'+sub+'</div></div><div class="test-cat-score-wrap">'+barFill+scoreDisp+'</div><span class="chevron">▾</span></div><div class="test-body">'+bodyHtml+'</div></div>';}
function toggleCat(header){var card=header.closest('.test-category');card.classList.toggle('open');}
var MODEL_PASSPORTS={
  'llama-3.1-8b':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'8B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'128k',mmlu:'73.0',humaneval:'72.6',gsm8k:'84.4',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct',quant:'GGUF, EXL2, AWQ',pricing:'$0.05 / $0.08'},
  'llama-3.3-70b':{developer:'Meta',released:'Dec 2024',license:'Llama 3.3 Community',params:'70B',arch:'Dense Transformer (GQA)',cutoff:'Dec 2023',context:'128k',mmlu:'86.0',humaneval:'88.4',gsm8k:'95.1',gpqa:'50.5',elo:'1255',hf:'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',quant:'GGUF, EXL2, AWQ',pricing:'$0.59 / $0.79'},
  'gpt-oss-120b':{developer:'OpenAI',released:'Jul 2025',license:'Apache 2.0',params:'120B (MoE, 5.1B active)',arch:'MoE Transformer (MXFP4)',cutoff:'Apr 2024',context:'128k',mmlu:'87.7',humaneval:'89.4',gsm8k:'96.6',gpqa:'62.3',elo:'1285',hf:'https://huggingface.co/openai/gpt-oss-120b',quant:'MXFP4 (native)',pricing:'$0.35 / $0.75'},
  'gpt-oss-20b':{developer:'OpenAI',released:'Jul 2025',license:'Apache 2.0',params:'20B',arch:'Dense Transformer',cutoff:'Apr 2024',context:'128k',mmlu:'79.4',humaneval:'79.8',gsm8k:'90.2',gpqa:null,elo:null,hf:'https://huggingface.co/openai/gpt-oss-20b',quant:'GGUF',pricing:'$0.10 / $0.25'},
  'llama-4-scout':{developer:'Meta',released:'Apr 2025',license:'Llama 4 Community',params:'17B (MoE, 109B total)',arch:'MoE Transformer',cutoff:'Feb 2025',context:'10M',mmlu:'79.6',humaneval:'80.4',gsm8k:'90.5',gpqa:'49.8',elo:'1240',hf:'https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct',quant:'GGUF, AWQ',pricing:'$0.11 / $0.34'},
  'qwen3-32b':{developer:'Alibaba / Qwen Team',released:'Apr 2025',license:'Apache 2.0',params:'32B',arch:'Dense Transformer (hybrid thinking)',cutoff:'Jun 2024',context:'32k',mmlu:'83.4',humaneval:'84.6',gsm8k:'94.8',gpqa:'53.1',elo:'1262',hf:'https://huggingface.co/Qwen/Qwen3-32B',quant:'GGUF, EXL2, AWQ',pricing:'$0.10 / $0.30'},
  'kimi-k2':{developer:'Moonshot AI',released:'Jul 2025',license:'Modified MIT',params:'MoE (details N/A)',arch:'MoE Transformer',cutoff:'Jun 2025',context:'128k',mmlu:'87.3',humaneval:'90.2',gsm8k:'97.1',gpqa:'66.1',elo:null,hf:'https://huggingface.co/moonshotai/Kimi-K2-Instruct',quant:'N/A',pricing:'$0.60 / $2.50'},
  'nemotron-super-120b':{developer:'NVIDIA',released:'Feb 2025',license:'NVIDIA Open Model',params:'120B (MoE, 12B active)',arch:'Hybrid SSM-Transformer (MoE)',cutoff:'Jan 2024',context:'128k',mmlu:'85.5',humaneval:'73.9',gsm8k:'93.0',gpqa:'55.7',elo:null,hf:'https://huggingface.co/nvidia/Llama-3.1-Nemotron-Super-49B-v1',quant:'GGUF',pricing:'Free'},
  'gemma-3-27b':{developer:'Google DeepMind',released:'Mar 2025',license:'Gemma ToU',params:'27B',arch:'Dense Transformer (multimodal)',cutoff:'Jun 2024',context:'128k',mmlu:'81.2',humaneval:'68.1',gsm8k:'89.7',gpqa:'43.6',elo:'1220',hf:'https://huggingface.co/google/gemma-3-27b-it',quant:'GGUF, AWQ',pricing:'Free'},
  'gemma-3-12b':{developer:'Google DeepMind',released:'Mar 2025',license:'Gemma ToU',params:'12B',arch:'Dense Transformer (multimodal)',cutoff:'Jun 2024',context:'128k',mmlu:'74.5',humaneval:'51.3',gsm8k:'79.4',gpqa:'38.2',elo:null,hf:'https://huggingface.co/google/gemma-3-12b-it',quant:'GGUF, AWQ',pricing:'Free'},
  'gemma-3-4b':{developer:'Google DeepMind',released:'Mar 2025',license:'Gemma ToU',params:'4B',arch:'Dense Transformer (multimodal)',cutoff:'Jun 2024',context:'128k',mmlu:'59.6',humaneval:'36.2',gsm8k:'61.8',gpqa:null,elo:null,hf:'https://huggingface.co/google/gemma-3-4b-it',quant:'GGUF',pricing:'Free'},
  'llama-3.2-3b':{developer:'Meta',released:'Sep 2024',license:'Llama 3.2 Community',params:'3B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'128k',mmlu:'63.4',humaneval:'52.3',gsm8k:'77.7',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct',quant:'GGUF, MLX',pricing:'Free'},
  'hermes-405b':{developer:'Nous Research',released:'Aug 2024',license:'Llama 3.1 Community',params:'405B',arch:'Dense Transformer (fine-tuned Llama 3.1)',cutoff:'Dec 2023',context:'128k',mmlu:'85.9',humaneval:'72.0',gsm8k:'94.1',gpqa:null,elo:null,hf:'https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-405B',quant:'GGUF',pricing:'Free'},
  'mistral-small-3.1':{developer:'Mistral AI',released:'Mar 2025',license:'Apache 2.0',params:'24B',arch:'Dense Transformer (multimodal)',cutoff:'Mar 2025',context:'128k',mmlu:'81.0',humaneval:'73.2',gsm8k:'88.5',gpqa:'42.1',elo:null,hf:'https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503',quant:'GGUF, AWQ',pricing:'Free'},
  'deepseek-r1-or':{developer:'DeepSeek',released:'Jan 2025',license:'MIT',params:'671B (MoE, 37B active)',arch:'MoE Transformer (CoT reasoning)',cutoff:'Jul 2024',context:'64k',mmlu:'90.8',humaneval:'92.5',gsm8k:'97.3',gpqa:'71.5',elo:'1358',hf:'https://huggingface.co/deepseek-ai/DeepSeek-R1',quant:'GGUF, EXL2',pricing:'Free'},
  'deepseek-v3-or':{developer:'DeepSeek',released:'Mar 2025',license:'MIT',params:'671B (MoE, 37B active)',arch:'MoE Transformer (MLA + DeepSeekMoE)',cutoff:'Jul 2024',context:'64k',mmlu:'88.5',humaneval:'89.3',gsm8k:'96.2',gpqa:'59.1',elo:'1320',hf:'https://huggingface.co/deepseek-ai/DeepSeek-V3-0324',quant:'GGUF',pricing:'Free'},
  'qwen2.5-72b-or':{developer:'Alibaba / Qwen Team',released:'Sep 2024',license:'Qwen Research',params:'72B',arch:'Dense Transformer',cutoff:'Sep 2024',context:'128k',mmlu:'86.1',humaneval:'80.5',gsm8k:'95.2',gpqa:'49.0',elo:'1290',hf:'https://huggingface.co/Qwen/Qwen2.5-72B-Instruct',quant:'GGUF, EXL2, AWQ',pricing:'Free'},
  'qwen2.5-coder-32b-or':{developer:'Alibaba / Qwen Team',released:'Nov 2024',license:'Apache 2.0',params:'32B',arch:'Dense Transformer (code-specialized)',cutoff:'Sep 2024',context:'32k',mmlu:'83.1',humaneval:'92.7',gsm8k:'91.5',gpqa:'41.3',elo:null,hf:'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct',quant:'GGUF, EXL2, AWQ',pricing:'Free'},
  'qwq-32b-or':{developer:'Alibaba / Qwen Team',released:'Mar 2025',license:'Apache 2.0',params:'32B',arch:'Dense Transformer (reasoning-focused)',cutoff:'Jun 2024',context:'32k',mmlu:'85.0',humaneval:'90.6',gsm8k:'96.2',gpqa:'65.2',elo:'1317',hf:'https://huggingface.co/Qwen/QwQ-32B',quant:'GGUF, EXL2, AWQ',pricing:'Free'},
  'llama-3.1-405b-or':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'405B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'128k',mmlu:'88.6',humaneval:'89.0',gsm8k:'96.8',gpqa:'51.1',elo:'1266',hf:'https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct',quant:'GGUF',pricing:'Free'},
  'llama-3.1-70b-or':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'70B',arch:'Dense Transformer (GQA)',cutoff:'Dec 2023',context:'128k',mmlu:'83.6',humaneval:'80.5',gsm8k:'93.0',gpqa:'46.7',elo:'1247',hf:'https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct',quant:'GGUF, EXL2, AWQ',pricing:'Free'},
  'llama-3.1-8b-or':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'8B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'128k',mmlu:'73.0',humaneval:'72.6',gsm8k:'84.4',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct',quant:'GGUF, MLX',pricing:'Free'},
  'llama-3.2-90b-or':{developer:'Meta',released:'Sep 2024',license:'Llama 3.2 Community',params:'90B',arch:'Dense Transformer (vision-language)',cutoff:'Dec 2023',context:'128k',mmlu:'86.0',humaneval:'72.0',gsm8k:'92.8',gpqa:'46.0',elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.2-90B-Vision-Instruct',quant:'GGUF',pricing:'Free'},
  'llama-3.2-11b-or':{developer:'Meta',released:'Sep 2024',license:'Llama 3.2 Community',params:'11B',arch:'Dense Transformer (vision-language)',cutoff:'Dec 2023',context:'128k',mmlu:'73.0',humaneval:'56.8',gsm8k:'88.0',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct',quant:'GGUF',pricing:'Free'},
  'llama-3.2-1b-or':{developer:'Meta',released:'Sep 2024',license:'Llama 3.2 Community',params:'1B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'128k',mmlu:'49.3',humaneval:'28.2',gsm8k:'44.4',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct',quant:'GGUF, MLX',pricing:'Free'},
  'gemini-2.5-flash':{developer:'Google DeepMind',released:'May 2025',license:'Proprietary',params:'N/A',arch:'Proprietary multimodal',cutoff:'Jan 2025',context:'1M',mmlu:'89.0',humaneval:'89.9',gsm8k:'97.0',gpqa:'72.0',elo:'1387',hf:null,quant:'N/A',pricing:'$0.15 / $0.60'},
  'gemini-2.5-flash-lite':{developer:'Google DeepMind',released:'Jun 2025',license:'Proprietary',params:'N/A',arch:'Proprietary multimodal (lite)',cutoff:'Jan 2025',context:'1M',mmlu:'81.0',humaneval:'78.4',gsm8k:'92.3',gpqa:'52.0',elo:null,hf:null,quant:'N/A',pricing:'$0.075 / $0.30'},
  'Qwen3-32B':{developer:'Alibaba / Qwen Team',released:'Apr 2025',license:'Apache 2.0',params:'32B',arch:'Dense Transformer (hybrid thinking)',cutoff:'Jun 2024',context:'8k',mmlu:'83.4',humaneval:'84.6',gsm8k:'94.8',gpqa:'53.1',elo:'1262',hf:'https://huggingface.co/Qwen/Qwen3-32B',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'DeepSeek-R1':{developer:'DeepSeek',released:'Jan 2025',license:'MIT',params:'671B (MoE, 37B active)',arch:'MoE Transformer (CoT reasoning)',cutoff:'Jul 2024',context:'32k',mmlu:'90.8',humaneval:'92.5',gsm8k:'97.3',gpqa:'71.5',elo:'1358',hf:'https://huggingface.co/deepseek-ai/DeepSeek-R1',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'DeepSeek-V3-0324':{developer:'DeepSeek',released:'Mar 2025',license:'MIT',params:'671B (MoE, 37B active)',arch:'MoE Transformer (MLA + DeepSeekMoE)',cutoff:'Jul 2024',context:'128k',mmlu:'88.5',humaneval:'89.3',gsm8k:'96.2',gpqa:'59.1',elo:'1320',hf:'https://huggingface.co/deepseek-ai/DeepSeek-V3-0324',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-4-Maverick-17B-128E-Instruct':{developer:'Meta',released:'Apr 2025',license:'Llama 4 Community',params:'17B (MoE, 128 experts)',arch:'MoE Transformer (vision)',cutoff:'Feb 2025',context:'1M',mmlu:'85.5',humaneval:'82.6',gsm8k:'93.2',gpqa:'69.8',elo:'1417',hf:'https://huggingface.co/meta-llama/Llama-4-Maverick-17B-128E-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-4-Scout-17B-16E-Instruct':{developer:'Meta',released:'Apr 2025',license:'Llama 4 Community',params:'17B (MoE, 16 experts)',arch:'MoE Transformer',cutoff:'Feb 2025',context:'10M',mmlu:'79.6',humaneval:'80.4',gsm8k:'90.5',gpqa:'49.8',elo:'1240',hf:'https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-3.3-70B-Instruct':{developer:'Meta',released:'Dec 2024',license:'Llama 3.3 Community',params:'70B',arch:'Dense Transformer (GQA)',cutoff:'Dec 2023',context:'128k',mmlu:'86.0',humaneval:'88.4',gsm8k:'95.1',gpqa:'50.5',elo:'1255',hf:'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-3.1-405B-Instruct':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'405B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'16k',mmlu:'88.6',humaneval:'89.0',gsm8k:'96.8',gpqa:'51.1',elo:'1266',hf:'https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-3.1-70B-Instruct':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'70B',arch:'Dense Transformer (GQA)',cutoff:'Dec 2023',context:'16k',mmlu:'83.6',humaneval:'80.5',gsm8k:'93.0',gpqa:'46.7',elo:'1247',hf:'https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Meta-Llama-3.1-8B-Instruct':{developer:'Meta',released:'Jul 2024',license:'Llama 3.1 Community',params:'8B',arch:'Dense Transformer',cutoff:'Dec 2023',context:'16k',mmlu:'73.0',humaneval:'72.6',gsm8k:'84.4',gpqa:null,elo:null,hf:'https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Qwen2.5-72B-Instruct':{developer:'Alibaba / Qwen Team',released:'Sep 2024',license:'Qwen Research',params:'72B',arch:'Dense Transformer',cutoff:'Sep 2024',context:'128k',mmlu:'86.1',humaneval:'80.5',gsm8k:'95.2',gpqa:'49.0',elo:'1290',hf:'https://huggingface.co/Qwen/Qwen2.5-72B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'Qwen2.5-Coder-32B-Instruct':{developer:'Alibaba / Qwen Team',released:'Nov 2024',license:'Apache 2.0',params:'32B',arch:'Dense Transformer (code-specialized)',cutoff:'Sep 2024',context:'128k',mmlu:'83.1',humaneval:'92.7',gsm8k:'91.5',gpqa:'41.3',elo:null,hf:'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct',quant:'N/A (SambaNova RDU)',pricing:'Free tier'},
  'nemotron-nano-30b':{developer:'NVIDIA',released:'Feb 2025',license:'NVIDIA Open Model',params:'30B (MoE, 3B active)',arch:'Hybrid SSM-Transformer (MoE)',cutoff:'Jan 2024',context:'128k',mmlu:'74.9',humaneval:'55.2',gsm8k:'82.3',gpqa:'35.1',elo:null,hf:'https://huggingface.co/nvidia/Llama-3.1-Nemotron-Nano-30B-v1',quant:'GGUF',pricing:'Free'},
  'nemotron-nano-12b':{developer:'NVIDIA',released:'Feb 2025',license:'NVIDIA Open Model',params:'12B',arch:'Dense Transformer',cutoff:'Jan 2024',context:'128k',mmlu:'71.4',humaneval:'52.8',gsm8k:'79.1',gpqa:'32.0',elo:null,hf:'https://huggingface.co/nvidia/Llama-3.2-Nemotron-Nano-12B-v1',quant:'GGUF',pricing:'Free'},
  'nemotron-nano-9b':{developer:'NVIDIA',released:'Feb 2025',license:'NVIDIA Open Model',params:'9B',arch:'Dense Transformer',cutoff:'Jan 2024',context:'128k',mmlu:'69.2',humaneval:'49.1',gsm8k:'75.4',gpqa:null,elo:null,hf:'https://huggingface.co/nvidia/Llama-3.2-Nemotron-Nano-9B-v1',quant:'GGUF',pricing:'Free'},
  'qwen3-coder':{developer:'Alibaba / Qwen Team',released:'Jul 2025',license:'Apache 2.0',params:'480B (MoE, 35B active)',arch:'MoE Transformer (code-specialized)',cutoff:'Jun 2025',context:'256k',mmlu:'88.2',humaneval:'97.1',gsm8k:'96.8',gpqa:'66.5',elo:null,hf:'https://huggingface.co/Qwen/Qwen3-Coder',quant:'GGUF',pricing:'Free'},
  'qwen3-next-80b':{developer:'Alibaba / Qwen Team',released:'Jul 2025',license:'Apache 2.0',params:'80B',arch:'Dense Transformer (hybrid thinking)',cutoff:'Jun 2025',context:'128k',mmlu:'87.5',humaneval:'90.2',gsm8k:'96.1',gpqa:'62.0',elo:null,hf:'https://huggingface.co/Qwen/Qwen3-Next-80B',quant:'GGUF',pricing:'Free'},
  'qwen3-4b':{developer:'Alibaba / Qwen Team',released:'Apr 2025',license:'Apache 2.0',params:'4B',arch:'Dense Transformer (hybrid thinking)',cutoff:'Jun 2024',context:'32k',mmlu:'69.4',humaneval:'65.1',gsm8k:'82.4',gpqa:'36.3',elo:null,hf:'https://huggingface.co/Qwen/Qwen3-4B',quant:'GGUF',pricing:'Free'},
};
function renderPassportSection(model){
  var p=MODEL_PASSPORTS[model.model_id]||MODEL_PASSPORTS[model.api_provider+'-'+model.model_id];
  if(!p){var keys=Object.keys(MODEL_PASSPORTS);for(var i=0;i<keys.length;i++){if(model.model_id&&model.model_id.toLowerCase().indexOf(keys[i].toLowerCase())!==-1){p=MODEL_PASSPORTS[keys[i]];break;}}}
  var isOpen=p&&p.license&&(p.license.toLowerCase().indexOf('apache')!==-1||p.license.toLowerCase().indexOf('mit')!==-1||p.license.toLowerCase().indexOf('llama')!==-1||p.license.toLowerCase().indexOf('gemma')!==-1);
  var isProp=p&&p.license&&p.license.toLowerCase().indexOf('proprietary')!==-1;
  function row(key,val){if(!val||val==='null'||val===null)return'';return '<div class="passport-row"><span class="passport-key">'+key+'</span><span class="passport-val">'+val+'</span></div>';}
  function link(url,text){if(!url)return null;return '<a href="'+url+'" target="_blank" rel="noopener">'+text+'</a>';}
  function bench(label,val){var isEmpty=!val||val===null;return '<div class="bench-item"><div class="bench-name">'+label+'</div><div class="bench-val'+(isEmpty?' na':'')+'">'+(isEmpty?'—':val+'%')+'</div></div>';}
  if(!p)return '<div class="passport-block"><div class="passport-header"><div><div class="passport-header-title">🪪 Model Passport</div><div class="passport-header-sub">Identification · Technical specs · Benchmarks · Pricing</div></div></div><div style="padding:18px 22px;font-size:13px;color:var(--text-secondary);">Passport data not yet available for this model.</div></div>';
  var licenseTag=isOpen?' <span class="passport-tag tag-open">Open Source</span>':isProp?' <span class="passport-tag tag-prop">Proprietary</span>':'';
  var hfLink=p.hf?link(p.hf,'🤗 HuggingFace'):null;
  return '<div class="passport-block"><div class="passport-header"><div><div class="passport-header-title">🪪 Model Passport</div><div class="passport-header-sub">Identification · Technical specs · Benchmarks · Pricing</div></div></div><div class="passport-groups"><div class="passport-group"><div class="passport-group-title">① Identification</div><div class="passport-rows">'+row('Developer',esc(p.developer||'—'))+row('Released',esc(p.released||'—'))+row('License',esc(p.license||'—')+licenseTag)+'</div></div><div class="passport-group"><div class="passport-group-title">② Technical Parameters</div><div class="passport-rows">'+row('Parameters',esc(p.params||model.size||'—'))+row('Context Window',esc(p.context||model.context||'—'))+row('Architecture',esc(p.arch||'—'))+row('Knowledge Cutoff',esc(p.cutoff||'—'))+'</div></div><div class="passport-group"><div class="passport-group-title">③ Official Benchmarks</div><div class="passport-bench-grid">'+bench('MMLU',p.mmlu)+bench('HumanEval',p.humaneval)+bench('GSM8K',p.gsm8k)+bench('GPQA',p.gpqa)+'</div>'+(p.elo?'<div style="margin-top:10px;font-size:12px;color:var(--text-secondary);">LMSYS ELO: <strong style="color:var(--color-primary);">'+p.elo+'</strong></div>':'')+'</div><div class="passport-group"><div class="passport-group-title">④ Performance &amp; Links</div><div class="passport-rows">'+row('API Pricing',esc(p.pricing||'—'))+row('Quantization',esc(p.quant||'—'))+(hfLink?row('Model Card',hfLink):'')+'</div></div></div><div class="passport-note">Benchmark scores are from official model cards and public evaluations. LMSYS ELO from Chatbot Arena leaderboard.</div></div>';
}
function renderPage(model){
  var t=model.tests;
  document.title=model.model_name+' — Klyxe';
  var sizeLabel={large:'🔴 Large',medium:'🟡 Medium',small:'🟢 Small'}[model.size_category]||model.size_category;
  var heroHtml='<div class="model-hero"><div class="model-hero-inner"><div class="breadcrumb"><a href="/rankings">Rankings</a> › '+esc(model.model_name)+'</div><div class="model-hero-name">'+esc(model.model_name)+'</div><div class="model-hero-meta"><span>🏢 '+esc(model.provider)+'</span><span>📐 '+esc(model.size)+' · '+sizeLabel+'</span><span>📖 '+esc(model.context)+' context</span><span>🗓 Tested '+new Date(model.timestamp).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})+'</span></div><div class="hero-scores"><div class="hero-score-chip chip-quality"><span>Quality</span><span class="chip-val">'+Math.round(model.quality_score)+'</span><span style="font-size:12px;color:var(--text-tertiary)">/100</span></div><div class="hero-score-chip chip-speed"><span>⚡ Speed</span><span class="chip-val">'+Math.round(model.raw_speed)+'</span><span style="font-size:12px;color:var(--text-tertiary)">tok/s</span></div><div class="hero-score-chip"><span>💻 Code</span><span class="chip-val" style="color:var(--color-on-surface)">'+Math.round((t.code&&t.code.avg_score)||0)+'</span><span style="font-size:12px;color:var(--text-tertiary)">/100</span></div><div class="hero-score-chip"><span>🧠 Reasoning</span><span class="chip-val" style="color:var(--color-on-surface)">'+Math.round((t.reasoning&&t.reasoning.score)||0)+'</span><span style="font-size:12px;color:var(--text-tertiary)">/100</span></div></div></div></div>';
  var sectionsHtml='<div class="detail-container">'+renderPassportSection(model)+'<h2 class="section-heading">📈 History (last 32 days)</h2><div class="history-section"><div class="history-chart-wrap"><canvas id="history-chart"></canvas></div><div class="history-legend"><div class="history-legend-item"><div class="history-legend-dot" style="background:#6366f1"></div>Quality Score</div><div class="history-legend-item"><div class="history-legend-dot" style="background:#10b981"></div>Speed (normalized)</div></div></div><h2 class="section-heading">🔬 Full Test Breakdown</h2><p style="font-size:13px;color:var(--text-secondary);margin-bottom:24px;line-height:1.6;">Click any category to expand the exact prompts, the model\'s responses, and how each answer was graded.</p>'+renderCodeSection(t)+renderReasoningSection(t)+renderInstructionSection(t)+renderTranslationSection(t)+renderSpeedSection(t)+'</div>';
  document.getElementById('page-root').innerHTML=heroHtml+sectionsHtml;
}
var params=new URLSearchParams(window.location.search);
var modelId=params.get('id');
if(!modelId){document.getElementById('page-root').innerHTML='<div class="page-error"><h2>No model specified</h2><p><a href="/rankings">← Back to rankings</a></p></div>';}else{
  fetch('data/results/latest.json').then(function(r){return r.json();}).then(function(data){
    var results=Array.isArray(data)?data:(data.results||[]);
    var model=results.find(function(m){return m.model_id===modelId;});
    if(!model){document.getElementById('page-root').innerHTML='<div class="page-error"><h2>Model not found</h2><p>ID: '+esc(modelId)+'</p><p><a href="/rankings">← Back to rankings</a></p></div>';}
    else{renderPage(model);loadHistoryChart(modelId);}
  }).catch(function(err){document.getElementById('page-root').innerHTML='<div class="page-error"><h2>Failed to load data</h2><p>'+esc(String(err))+'</p><p><a href="/rankings">← Back to rankings</a></p></div>';});
}
function loadHistoryChart(modelId){
  var dates=[];var d=new Date();
  for(var i=31;i>=0;i--){var dd=new Date(d);dd.setDate(d.getDate()-i);dates.push(dd.toISOString().split('T')[0]);}
  var promises=dates.map(function(date){return fetch('data/results/'+date+'.json').then(function(r){return r.ok?r.json():null;}).then(function(data){if(!data)return{date:date,quality:null,speed:null};var results=Array.isArray(data)?data:(data.results||[]);var m=results.find(function(x){return x.model_id===modelId;});return{date:date,quality:m?(m.quality_score||0):null,speed:m?(m.raw_speed||(m.tests&&m.tests.speed&&m.tests.speed.avg_tokens_per_sec)||0):null};}).catch(function(){return{date:date,quality:null,speed:null};});});
  Promise.all(promises).then(function(rows){
    var canvas=document.getElementById('history-chart');if(!canvas)return;
    var labels=rows.map(function(r){var dt=new Date(r.date+'T00:00:00');return (dt.getMonth()+1)+'/'+dt.getDate();});
    var qualityData=rows.map(function(r){return r.quality;});
    var speedData=rows.map(function(r){return r.speed;});
    var maxSpeed=Math.max.apply(null,speedData.filter(function(v){return v!==null;}))||1;
    var speedNorm=speedData.map(function(v){return v===null?null:Math.round(v/maxSpeed*100);});
    var dark=document.documentElement.getAttribute('data-theme')==='dark';
    var gridColor=dark?'rgba(255,255,255,0.07)':'rgba(0,0,0,0.06)';
    var tickColor=dark?'rgba(255,255,255,0.4)':'rgba(0,0,0,0.4)';
    new Chart(canvas,{type:'line',data:{labels:labels,datasets:[{label:'Quality Score',data:qualityData,borderColor:'#6366f1',backgroundColor:'rgba(99,102,241,0.08)',borderWidth:2,pointRadius:3,pointHoverRadius:5,pointBackgroundColor:'#6366f1',fill:true,tension:0.3,spanGaps:false},{label:'Speed (norm.)',data:speedNorm,borderColor:'#10b981',backgroundColor:'rgba(16,185,129,0.06)',borderWidth:2,pointRadius:3,pointHoverRadius:5,pointBackgroundColor:'#10b981',fill:false,tension:0.3,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{callbacks:{label:function(ctx){if(ctx.datasetIndex===0)return' Quality: '+(ctx.raw!==null?ctx.raw.toFixed(1):'N/A');var idx=ctx.dataIndex;var rawSpeed=rows[idx]?rows[idx].speed:null;return' Speed: '+(rawSpeed!==null?Math.round(rawSpeed)+' tok/s':'N/A');}}}},scales:{x:{grid:{color:gridColor},ticks:{color:tickColor,font:{size:11},maxTicksLimit:16}},y:{min:0,max:100,grid:{color:gridColor},ticks:{color:tickColor,font:{size:11}}}}}});
  });
}
      `}</Script>
    </>
  );
}
